apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/jprie/dispatcher-service/k8s?ref=main

#patches:
#  - path: patch-env.yml

#configMapGenerator:
#  - behavior: merge
#    files:
#      - application-staging.yml
#    name: catalog-config

images:
  - name: dispatcher-service
    newName: ghcr.io/jprie/dispatcher-service
    newTag: latest

replicas:
  - count: 2
    name: dispatcher-service

