polar:
  greeting: Welcome to our book catalog from production Kubernetes environment!
spring:
  config:
    import: configtree:/workspace/secrets/*/
logging:
  level:
    org.springframework.jdbc: debug