apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          volumeMounts:
            - mountPath: /workspace/secrets/postgres
              name: postgres-credentials-volume
            - mountPath: /workspace/secrets/keycloak
              name: keycloak-issuer-resourceserver-secret-volume
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: polar-postgres-catalog-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret
